/** Generated by scripts/generate-field-population.mjs. Full primary +
 * coeval companion mass/light per individual field object, including the
 * .013-M☉ clamp atom. Do not tune this table for display brightness. */
export const fieldPopulationTable = {
  "thin-disk": {
    "massSolar": 0.2484029224735375,
    "luminositySolar": 0.427096949000299,
    "opticalRgbSolar": [
      0.15179172141832412,
      0.1318837985032753,
      0.13901559165318578
    ]
  },
  "thick-disk": {
    "massSolar": 0.23027806329366352,
    "luminositySolar": 0.11177639683557951,
    "opticalRgbSolar": [
      0.04601903345509704,
      0.03278480847974891,
      0.02249093222028241
    ]
  },
  "halo": {
    "massSolar": 0.2283519749131997,
    "luminositySolar": 0.10168922804927046,
    "opticalRgbSolar": [
      0.0414754730434119,
      0.029215033481022303,
      0.019600927653340736
    ]
  },
  "bulge": {
    "massSolar": 0.22959195123803683,
    "luminositySolar": 0.1082315806184075,
    "opticalRgbSolar": [
      0.04442491285007944,
      0.031537793103351655,
      0.021489623421832568
    ]
  }
} as const;
