/** Generated by npm run generate:population from the full IMF, component
 * age laws and stellar evolution tracks at 256 mass bins. Do not tune these
 * values for display brightness. populationMoments.test.ts checks the model. */
export const populationMomentTable = {
  "thin-disk": {
    "massSolar": 0.25631567586731974,
    "luminositySolar": 0.4117619893552598,
    "opticalRgbSolar": [
      0.14746650484664298,
      0.12774715217500848,
      0.13379142319283352
    ]
  },
  "thick-disk": {
    "massSolar": 0.23846183962258605,
    "luminositySolar": 0.11516037454196157,
    "opticalRgbSolar": [
      0.047438843701551506,
      0.03380801581904488,
      0.023204400779711195
    ]
  },
  "halo": {
    "massSolar": 0.23648898788093672,
    "luminositySolar": 0.10532741674382705,
    "opticalRgbSolar": [
      0.04297873659078869,
      0.03028154306341478,
      0.020323558403523238
    ]
  },
  "bulge": {
    "massSolar": 0.2377579584543693,
    "luminositySolar": 0.11169561465473547,
    "opticalRgbSolar": [
      0.045870109278119284,
      0.032573412623744226,
      0.0222044426169833
    ]
  },
  "nuclear-young": {
    "massSolar": 0.32727715458535994,
    "luminositySolar": 17.911808084375814,
    "opticalRgbSolar": [
      2.4542255357518363,
      2.503045864188001,
      3.579009978802039
    ]
  }
} as const;
